"use client"

import React, { useState, useEffect, useCallback } from "react"
import { Copy, Check, Download, Plus, Trash2, Shield, ShieldAlert, Sparkles, FileText, CheckCircle2, AlertTriangle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { 
  Select, 
  SelectContent, 
  SelectItem, 
  SelectTrigger, 
  SelectValue 
} from "@/components/ui/select"
import { cn } from "@/lib/utils"

interface RobotDirective {
  bot: string
  type: "allow" | "disallow"
  path: string
}

export function RobotsGenerator() {
  const [sitemapUrl, setSitemapUrl] = useState("")
  const [disallowAll, setDisallowAll] = useState(false)
  const [customRules, setCustomRules] = useState<RobotDirective[]>([
    { bot: "*", type: "disallow", path: "/admin/" },
    { bot: "*", type: "disallow", path: "/api/" },
    { bot: "GPTBot", type: "disallow", path: "/" },
  ])

  // Validator States
  const [testPath, setTestPath] = useState("")
  const [testUserAgent, setTestUserAgent] = useState("*")
  const [validationResult, setValidationResult] = useState<{ allowed: boolean; matchedRule?: string } | null>(null)
  
  const [activeTab, setActiveTab] = useState<"code" | "validator">("code")
  const [copied, setCopied] = useState(false)

  // Generate output text
  const robotsTxtContent = React.useMemo(() => {
    let output = "# robots.txt generated by TheWordOf Tools (https://thewordof.com)\n"
    if (sitemapUrl.trim()) {
      output += `Sitemap: ${sitemapUrl.trim()}\n\n`
    }

    if (disallowAll) {
      output += "User-agent: *\n"
      output += "Disallow: /\n"
      return output
    }

    // Group rules by user-agent
    const grouped: { [key: string]: RobotDirective[] } = {}
    customRules.forEach(rule => {
      const agent = rule.bot.trim() || "*"
      if (!grouped[agent]) grouped[agent] = []
      grouped[agent].push(rule)
    })

    // Output * first if exists
    const agents = Object.keys(grouped).sort((a, b) => {
      if (a === "*") return -1
      if (b === "*") return 1
      return a.localeCompare(b)
    })

    agents.forEach(agent => {
      output += `User-agent: ${agent}\n`
      grouped[agent].forEach(rule => {
        const typeStr = rule.type === "allow" ? "Allow" : "Disallow"
        output += `${typeStr}: ${rule.path.trim() || "/"}\n`
      })
      output += "\n"
    })

    return output.trim()
  }, [sitemapUrl, disallowAll, customRules])

  // Run validation
  const runValidation = useCallback(() => {
    if (!testPath) {
      setValidationResult(null)
      return
    }

    const pathToCheck = testPath.trim()
    
    if (disallowAll) {
      setValidationResult({
        allowed: false,
        matchedRule: "Disallow: / (under global block)"
      })
      return
    }

    // Filter applicable directives
    const targetAgent = testUserAgent.trim() || "*"
    const matchingDirectives = customRules.filter(r => 
      r.bot.trim() === targetAgent || r.bot.trim() === "*"
    )

    // Sort by path specificity (longest path matches first)
    matchingDirectives.sort((a, b) => b.path.length - a.path.length)

    for (let rule of matchingDirectives) {
      const rulePath = rule.path.trim()
      if (!rulePath) continue

      // Wildcard matcher support
      const escapedPattern = rulePath.replace(/[-\/\\^$+?.()|[\]{}]/g, "\\$&").replace(/\\\*/g, ".*")
      const regex = new RegExp(`^${escapedPattern}`)

      if (regex.test(pathToCheck) || pathToCheck.startsWith(rulePath)) {
        setValidationResult({
          allowed: rule.type === "allow",
          matchedRule: `${rule.type === "allow" ? "Allow" : "Disallow"}: ${rulePath} (matched for ${rule.bot})`
        })
        return
      }
    }

    // Default Allow if no rule matched
    setValidationResult({ allowed: true, matchedRule: "Default allow (no disallow rules matched)" })
  }, [testPath, testUserAgent, customRules, disallowAll])

  useEffect(() => {
    runValidation()
  }, [testPath, testUserAgent, customRules, disallowAll])

  const copyToClipboard = () => {
    navigator.clipboard.writeText(robotsTxtContent)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadTxt = () => {
    const element = document.createElement("a")
    const file = new Blob([robotsTxtContent], {type: 'text/plain'})
    element.href = URL.createObjectURL(file)
    element.download = "robots.txt"
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const addRule = () => {
    setCustomRules([...customRules, { bot: "*", type: "disallow", path: "/" }])
  }

  const removeRule = (idx: number) => {
    setCustomRules(customRules.filter((_, i) => i !== idx))
  }

  const updateRule = (idx: number, field: keyof RobotDirective, value: string) => {
    setCustomRules(prev => {
      const next = [...prev]
      next[idx] = { ...next[idx], [field]: value } as RobotDirective
      return next
    })
  }

  // Presets handlers
  const applyPreset = (type: "allow-all" | "block-all" | "block-ai" | "nextjs" | "wordpress") => {
    setDisallowAll(false)
    if (type === "allow-all") {
      setCustomRules([])
    } else if (type === "block-all") {
      setDisallowAll(true)
    } else if (type === "block-ai") {
      setCustomRules([
        { bot: "GPTBot", type: "disallow", path: "/" },
        { bot: "ChatGPT-User", type: "disallow", path: "/" },
        { bot: "CCBot", type: "disallow", path: "/" },
        { bot: "Anthropic-AI", type: "disallow", path: "/" },
        { bot: "Google-Extended", type: "disallow", path: "/" }
      ])
    } else if (type === "nextjs") {
      setCustomRules([
        { bot: "*", type: "disallow", path: "/_next/" },
        { bot: "*", type: "disallow", path: "/api/" },
        { bot: "*", type: "allow", path: "/_next/static/" }
      ])
    } else if (type === "wordpress") {
      setCustomRules([
        { bot: "*", type: "disallow", path: "/wp-admin/" },
        { bot: "*", type: "allow", path: "/wp-admin/admin-ajax.php" }
      ])
    }
  }

  return (
    <div className="grid lg:grid-cols-2 gap-8 items-start">
      {/* Editor Column */}
      <div className="space-y-6">
        <Card className="border-none shadow-sm bg-muted/20">
          <CardHeader className="bg-muted/30 border-b pb-4">
            <CardTitle className="text-lg flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              Configure Crawler Directives
            </CardTitle>
            <CardDescription className="text-xs">Setup crawling rules, sitemaps, and user-agents.</CardDescription>
          </CardHeader>
          <CardContent className="p-6 space-y-5">
            {/* Sitemap */}
            <div className="space-y-2">
              <Label htmlFor="sitemap">Sitemap URL</Label>
              <Input 
                id="sitemap" 
                placeholder="https://example.com/sitemap.xml" 
                value={sitemapUrl}
                onChange={e => setSitemapUrl(e.target.value)}
              />
            </div>

            {/* Presets */}
            <div className="space-y-2">
              <Label>Quick Presets</Label>
              <div className="flex flex-wrap gap-2">
                <Button type="button" variant="outline" size="sm" className="text-xs font-bold" onClick={() => applyPreset("allow-all")}>Allow All</Button>
                <Button type="button" variant="outline" size="sm" className="text-xs font-bold text-red-500 border-red-500/20" onClick={() => applyPreset("block-all")}>Block All</Button>
                <Button type="button" variant="outline" size="sm" className="text-xs font-bold text-amber-600 border-amber-500/20" onClick={() => applyPreset("block-ai")}>Block AI Scrapers</Button>
                <Button type="button" variant="outline" size="sm" className="text-xs font-bold" onClick={() => applyPreset("nextjs")}>Next.js Default</Button>
                <Button type="button" variant="outline" size="sm" className="text-xs font-bold" onClick={() => applyPreset("wordpress")}>WordPress</Button>
              </div>
            </div>

            <hr className="border-border" />

            {/* Custom Rules */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label className="text-sm font-bold">Crawler Rules</Label>
                <Button type="button" variant="outline" size="sm" className="h-8 text-xs font-bold gap-1 cursor-pointer" onClick={addRule}>
                  <Plus className="h-3 w-3" /> Add Rule
                </Button>
              </div>

              {disallowAll ? (
                <div className="p-4 rounded-xl border border-red-500/10 bg-red-500/5 text-xs text-red-500 font-medium flex gap-2">
                  <ShieldAlert className="h-4 w-4 shrink-0" />
                  <span>A global block directive is active. No other crawl directives will be processed by Google.</span>
                </div>
              ) : (
                <div className="space-y-3 max-h-[300px] overflow-y-auto custom-scrollbar pr-1">
                  {customRules.map((rule, idx) => (
                    <div key={idx} className="flex gap-2 items-center bg-background p-2.5 rounded-xl border border-border">
                      <Input 
                        placeholder="Bot (e.g. *)" 
                        value={rule.bot}
                        onChange={e => updateRule(idx, "bot", e.target.value)}
                        className="w-1/3 h-9 text-xs"
                      />
                      <Select 
                        value={rule.type}
                        onValueChange={val => { if (val) updateRule(idx, "type", val) }}
                      >
                        <SelectTrigger className="w-1/4 h-9 text-xs">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="disallow">Disallow</SelectItem>
                          <SelectItem value="allow">Allow</SelectItem>
                        </SelectContent>
                      </Select>
                      <Input 
                        placeholder="Path (e.g. /admin/)" 
                        value={rule.path}
                        onChange={e => updateRule(idx, "path", e.target.value)}
                        className="w-1/3 h-9 text-xs"
                      />
                      <Button 
                        type="button"
                        variant="ghost" 
                        size="icon" 
                        className="text-muted-foreground hover:text-red-500 h-9 w-9 shrink-0 cursor-pointer"
                        onClick={() => removeRule(idx)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  ))}
                  {customRules.length === 0 && (
                    <p className="text-xs text-muted-foreground text-center py-6">No custom directives added. Crawler will index all paths by default.</p>
                  )}
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Output & Validator Column */}
      <div className="space-y-4 sticky top-4">
        {/* Tab Controls */}
        <div className="flex items-center justify-between bg-card p-1.5 border border-border rounded-xl">
          <div className="flex gap-1.5">
            <button 
              type="button"
              onClick={() => setActiveTab("code")}
              className={cn(
                "px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer",
                activeTab === "code" ? "bg-primary text-primary-foreground shadow-sm" : "hover:bg-muted text-muted-foreground"
              )}
            >
              robots.txt File
            </button>
            <button 
              type="button"
              onClick={() => setActiveTab("validator")}
              className={cn(
                "px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer",
                activeTab === "validator" ? "bg-primary text-primary-foreground shadow-sm" : "hover:bg-muted text-muted-foreground"
              )}
            >
              Interactive Path Tester
            </button>
          </div>
          
          {activeTab === "code" && (
            <div className="flex gap-1">
              <Button type="button" variant="outline" size="sm" className="h-8 text-xs font-bold gap-1" onClick={copyToClipboard}>
                {copied ? <Check className="h-3 w-3 text-green-500" /> : <Copy className="h-3 w-3" />}
                {copied ? "Copied" : "Copy"}
              </Button>
              <Button type="button" variant="outline" size="sm" className="h-8 text-xs font-bold gap-1" onClick={downloadTxt}>
                <Download className="h-3 w-3" /> Download
              </Button>
            </div>
          )}
        </div>

        {activeTab === "code" ? (
          <div className="relative">
            <pre className="bg-zinc-950 text-zinc-300 p-6 rounded-3xl overflow-x-auto text-xs font-mono whitespace-pre-wrap min-h-[350px] shadow-sm leading-relaxed border border-white/5 animate-in fade-in duration-200">
              {robotsTxtContent}
            </pre>
          </div>
        ) : (
          <Card className="border-none shadow-sm bg-card p-6 min-h-[350px] animate-in fade-in duration-200 space-y-6">
            <div className="space-y-4">
              <h3 className="text-sm font-black uppercase tracking-widest text-muted-foreground">Test URL Accessibility</h3>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <Label htmlFor="test-bot">User-Agent</Label>
                  <Select value={testUserAgent} onValueChange={val => { if (val) setTestUserAgent(val) }}>
                    <SelectTrigger id="test-bot" className="h-10 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="*">All Bots (*)</SelectItem>
                      <SelectItem value="Googlebot">Googlebot</SelectItem>
                      <SelectItem value="Bingbot">Bingbot</SelectItem>
                      <SelectItem value="AhrefsBot">AhrefsBot</SelectItem>
                      <SelectItem value="GPTBot">GPTBot (AI)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1">
                  <Label htmlFor="test-path">Path to Test</Label>
                  <Input 
                    id="test-path" 
                    placeholder="e.g. /admin/dashboard" 
                    value={testPath}
                    onChange={e => setTestPath(e.target.value)}
                    className="h-10 text-xs"
                  />
                </div>
              </div>

              {validationResult && (
                <div className={cn(
                  "p-5 rounded-2xl border flex gap-4 items-start duration-300 transition-all",
                  validationResult.allowed 
                    ? "bg-green-500/[0.03] border-green-500/10 text-green-700" 
                    : "bg-red-500/[0.03] border-red-500/10 text-red-600"
                )}>
                  {validationResult.allowed ? (
                    <CheckCircle2 className="h-6 w-6 shrink-0 text-green-500" />
                  ) : (
                    <ShieldAlert className="h-6 w-6 shrink-0 text-red-500" />
                  )}
                  <div className="space-y-1 text-xs">
                    <p className="font-black text-sm">
                      Path is {validationResult.allowed ? "ALLOWED" : "BLOCKED"} for {testUserAgent}
                    </p>
                    <p className="text-[#4d5156] font-medium leading-relaxed">
                      Rule directive matching: <code className="font-mono bg-muted px-1.5 py-0.5 rounded border border-border text-[10px]">{validationResult.matchedRule}</code>
                    </p>
                  </div>
                </div>
              )}
            </div>
          </Card>
        )}
      </div>

      {/* SEO/Footer cards */}
      <div className="lg:col-span-2 grid md:grid-cols-3 gap-6 mt-8">
        <div className="bg-primary/5 border border-primary/10 p-5 rounded-2xl space-y-2">
          <h4 className="text-sm font-bold flex items-center gap-2">
            <span className="h-5 w-5 rounded-lg bg-primary/10 flex items-center justify-center text-primary"><span className="text-[10px] font-black">1</span></span> Configure Directives
          </h4>
          <p className="text-xs text-muted-foreground leading-relaxed">
            Manage sitemaps and specific crawling constraints for Googlebot, Bingbot, or blocker rules targeting AI scrapers (e.g. GPTBot).
          </p>
        </div>
        <div className="bg-primary/5 border border-primary/10 p-5 rounded-2xl space-y-2">
          <h4 className="text-sm font-bold flex items-center gap-2">
            <span className="h-5 w-5 rounded-lg bg-primary/10 flex items-center justify-center text-primary"><span className="text-[10px] font-black">2</span></span> Syntax Validation
          </h4>
          <p className="text-xs text-muted-foreground leading-relaxed">
            Enter test URL paths to evaluate crawler matching rules locally. Instantly check if critical paths are crawlable.
          </p>
        </div>
        <div className="bg-primary/5 border border-primary/10 p-5 rounded-2xl space-y-2">
          <h4 className="text-sm font-bold flex items-center gap-2">
            <span className="h-5 w-5 rounded-lg bg-primary/10 flex items-center justify-center text-primary"><span className="text-[10px] font-black">3</span></span> SEO Best Practices
          </h4>
          <p className="text-xs text-muted-foreground leading-relaxed">
            Ensure search crawlers do not waste budget indexing dev environments, sensitive profile APIs, or temporary files.
          </p>
        </div>
      </div>
    </div>
  )
}
